"""Create schema ``app`` and table ``app.feedback`` for 👍/👎 feedback.

Revision ID: 005
Revises: 004
Create Date: 2026-05-02

app-day-26: introduces a separate Postgres schema ``app`` for runtime
application data (feedback, in the future audit_log, sessions, rate
limit buckets) so it stays cleanly separated from the corpus tables in
``public`` (work / expression / instance / chunk + lookups).

The ``feedback`` table is keyed by ``trace_id`` (UUID4 generated by
``AnswerService`` per request). PRIMARY KEY on ``trace_id`` makes the
``POST /api/feedback`` endpoint naturally idempotent — a re-vote on
the same trace updates the row instead of creating a new one.

Snapshotted columns (``query_text``, ``answer_text``, ``llm_model``,
``style``, ``pipeline_version``, ``latency_ms``, token counts) duplicate
data already present in logs / Phoenix spans. We accept the duplication
because feedback review through ``psql`` should not require joining
against an audit_log table that does not exist yet (planned for
app-day-49).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "005"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    op.create_table(
        "feedback",
        sa.Column("trace_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("thumb", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("pipeline_version", sa.String(64), nullable=False),
        sa.Column("llm_model", sa.String(128), nullable=False),
        sa.Column("style", sa.String(16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("llm_tokens_in", sa.Integer(), nullable=False),
        sa.Column("llm_tokens_out", sa.Integer(), nullable=False),
        sa.CheckConstraint("thumb IN (-1, 1)", name="ck_feedback_thumb"),
        schema="app",
    )
    # Three indexes covering the typical review queries:
    #   * ``ts DESC``               — "feedback за неделю"
    #   * ``thumb, ts DESC``        — "все 👎 за неделю"
    #   * ``llm_model``             — "доля 👎 у разных моделей"
    op.create_index(
        "idx_feedback_ts",
        "feedback",
        [sa.text("ts DESC")],
        schema="app",
    )
    op.create_index(
        "idx_feedback_thumb_ts",
        "feedback",
        ["thumb", sa.text("ts DESC")],
        schema="app",
    )
    op.create_index(
        "idx_feedback_llm_model",
        "feedback",
        ["llm_model"],
        schema="app",
    )


def downgrade() -> None:
    op.drop_index("idx_feedback_llm_model", table_name="feedback", schema="app")
    op.drop_index("idx_feedback_thumb_ts", table_name="feedback", schema="app")
    op.drop_index("idx_feedback_ts", table_name="feedback", schema="app")
    op.drop_table("feedback", schema="app")
    op.execute("DROP SCHEMA IF EXISTS app")
