"""Add Contextual Retrieval columns to chunk.

Revision ID: 004
Revises: 003
Create Date: 2026-04-27

Day-16 plan: store the LLM-generated context per child chunk, plus
versioning metadata so future re-context migrations can target only
the rows whose ``context_version`` differs from the current default.

Three new columns
-----------------
* ``context_text``        — the 50-100 token paragraph generated by the
  LLM. Nullable: parent chunks and pre-day-16 rows have no context.
* ``context_version``     — short string like ``"v1-2026-04-27"``
  identifying the prompt that produced this context. Bumped when the
  prompt itself changes (rare); allows partial re-runs.
* ``context_model``       — provider/model identifier like
  ``"openrouter/anthropic/claude-3.5-haiku"``. Bumped when the
  generating model changes; allows A/B between providers.

All three are NULL before day-16 backfill runs, and remain NULL on
parent chunks (only children are contextualized — parents are the
*input* to context generation, not the output).

We deliberately do NOT add an index here. ``context_version`` is
queried only by maintenance scripts (``WHERE context_version IS NULL
OR context_version <> 'v1'``) which are batch jobs, not hot-path
reads. Adding an index would just slow down INSERT throughput on the
day-16 industrial run for no read benefit.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "chunk",
        sa.Column("context_text", sa.Text(), nullable=True),
    )
    op.add_column(
        "chunk",
        sa.Column("context_version", sa.String(64), nullable=True),
    )
    op.add_column(
        "chunk",
        sa.Column("context_model", sa.String(128), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("chunk", "context_model")
    op.drop_column("chunk", "context_version")
    op.drop_column("chunk", "context_text")
