"""Dump the FastAPI app's OpenAPI 3.x spec to ``openapi.json`` at repo root.

Why a checked-in artifact rather than just dynamic ``/openapi.json``
during dev:

* **Reviewable contract diffs.** Any change to a Pydantic schema in
  ``src/api/`` produces a diff in ``openapi.json`` — the PR reviewer
  sees the contract change explicitly, not just the model.
* **Frontend doesn't need backend running.** ``web/lib/api-types.ts``
  is generated by ``openapi-typescript openapi.json -o ...``. No
  uvicorn, no Postgres, no Qdrant required.
* **CI guard.** A simple "is openapi.json in sync with the live app?"
  check catches accidental schema drift before merge.

Usage::

    python scripts/export_openapi.py            # writes ./openapi.json
    python scripts/export_openapi.py --check    # exit 1 if file is stale

Run via ``pnpm gen:openapi`` (Node monorepo entry point).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Stub mode is the lightest backend that still exposes the full
# contract — we don't need Postgres/Qdrant just to introspect schemas.
import os  # noqa: E402

os.environ.setdefault("RAG_BACKEND", "stub")

from src.api.app import create_app  # noqa: E402

DEFAULT_OUT_PATH: Path = _REPO_ROOT / "openapi.json"


def _generate() -> dict[str, object]:
    app = create_app()
    spec = app.openapi()
    # Stable key ordering and 2-space indent so diffs are minimal across
    # runs. ``ensure_ascii=False`` keeps Russian text in descriptions
    # intact rather than ``\u``-escaped.
    return spec


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT_PATH, help="Output path.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the on-disk file differs from the live spec.",
    )
    args = parser.parse_args()

    spec = _generate()
    rendered = json.dumps(spec, indent=2, ensure_ascii=False, sort_keys=True) + "\n"

    if args.check:
        if not args.out.exists():
            print(
                f"ERROR: {args.out} does not exist. "
                "Run `python scripts/export_openapi.py` and commit it.",
                file=sys.stderr,
            )
            return 1
        existing = args.out.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"ERROR: {args.out} is stale. "
                "Run `python scripts/export_openapi.py` to refresh "
                "and commit the diff.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} matches live spec.")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.out} ({len(rendered):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
