"""Ingest Dharmaseed transcripts into the Dharma-RAG corpus (rag-day-37).

Pilot: Rob Burbea (461 talks at ``Q:\\dharmaseed\\transcripts\\rob_burbea\\``).
Variant A from concept-37 — single ``dharma_v2`` Qdrant collection,
``Work.source_type='dharmaseed_talk'`` payload tag drives the
per-corpus filter on retrieval. Deterministic context prefix (no LLM
round-trip) — see concept-37 §4.4 for rationale.

Usage::

    python scripts/ingest_dharmaseed.py \\
        --teacher-slug rob_burbea \\
        --transcripts-dir Q:/dharmaseed/transcripts/rob_burbea \\
        --talks-json Q:/dharmaseed/rob_burbea_talks.json

Idempotent: re-running on the same transcripts produces zero new
inserts (content_hash match → skip). Adding a new talk later? Same
command — only the new file gets inserted.

License/consent:
* Default `Expression.license = 'CC-BY-NC-ND-4.0'`
* `Expression.consent_ledger_ref = 'local-dev/dharmaseed-{teacher}-pilot.yaml'`
  → marker that this is local-dev only; a public-launch ingest must
  flip the ref to a populated ledger entry. See concept-37 §«Лицензии».
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import re
import sys
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import UUID

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import sqlalchemy as sa  # noqa: E402
from sqlalchemy.ext.asyncio import (  # noqa: E402
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from src.config import get_settings  # noqa: E402
from src.db.models.frbr import Chunk, Expression, Instance, Work  # noqa: E402
from src.db.models.lookups import Author  # noqa: E402
from src.processing.cleaner import to_ascii_fold  # noqa: E402
from src.processing.talk_chunker import chunk_talk  # noqa: E402

logger = logging.getLogger(__name__)


_HEADER_END_RE = re.compile(r"^TRANSCRIPTION:\s*$", re.MULTILINE)
_FOOTER_START_RE = re.compile(r"^Generated by WhisperAI\s*$", re.MULTILINE)
_FILENAME_RE = re.compile(r"^([a-z]+)_(\d+)_(.+)\.txt$")


@dataclass(slots=True)
class TalkRecord:
    """Parsed transcript + matching metadata, ready for FRBR insert."""

    canonical_id: str  # e.g. "rb_12345"
    dharmaseed_id: str  # raw id from talks.json
    title: str
    date_iso: str  # YYYY-MM-DD or empty if unknown
    body: str  # transcript body, header/footer stripped
    body_hash: str  # sha256 of cleaned body — stable identity
    file_path: Path  # original .txt for storage_path provenance
    talk_meta: dict[str, Any]  # raw entry from talks.json (for archival)


@dataclass(slots=True)
class IngestStats:
    talks_seen: int = 0
    talks_inserted: int = 0
    talks_skipped: int = 0
    talks_errored: int = 0
    parents_inserted: int = 0
    children_inserted: int = 0


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _strip_transcript(raw: str) -> str:
    """Drop WhisperAI report header + footer, return prose body only."""
    header_match = _HEADER_END_RE.search(raw)
    if header_match is None:
        # No "TRANSCRIPTION:" line — return everything except trailing
        # generator boilerplate. Defensive — handles non-standard
        # outputs from older WhisperAI runs.
        body = raw
    else:
        body = raw[header_match.end() :]
    footer_match = _FOOTER_START_RE.search(body)
    if footer_match is not None:
        body = body[: footer_match.start()]
    return body.strip()


def _parse_filename(filename: str) -> tuple[str, str, str] | None:
    """Extract (teacher_slug, dharmaseed_id, title_slug) from a filename.

    Burbea files look like ``rb_10024_emotions_and_freedom.txt``;
    Sucitto files like ``as_10231_opening_the_door.txt``. Returns
    None when the filename does not match the convention so the
    caller can either skip or surface a warning.
    """
    m = _FILENAME_RE.match(filename)
    if m is None:
        return None
    return m.group(1), m.group(2), m.group(3)


def _build_talks_index(talks_json_path: Path) -> dict[str, dict[str, Any]]:
    """Parse the per-teacher talks.json into ``id → entry`` lookup.

    `id` is the dharmaseed talk-id (string). When an entry's `name`
    field disagrees with the file naming convention we still match by
    id — newer transcripts sometimes have the canonical filename ahead
    of a metadata refresh.
    """
    raw = json.loads(talks_json_path.read_text(encoding="utf-8"))
    return {entry["id"]: entry for entry in raw if "id" in entry}


def _build_talk_record(
    *,
    txt_path: Path,
    talks_index: dict[str, dict[str, Any]],
    teacher_slug: str,
) -> TalkRecord | None:
    """Parse a single transcript .txt + match its metadata.

    The filename prefix is a Dharmaseed convention (e.g. ``rb_`` for
    Burbea, ``as_`` for Sucitto) and need not match the author slug
    in ``author_t``. We accept any ``<prefix>_<id>_<title>.txt`` form
    and rely on the per-teacher ``talks.json`` (constructed from the
    same source) to provide authoritative metadata.
    """
    parsed = _parse_filename(txt_path.name)
    if parsed is None:
        logger.warning("Skipping unrecognised filename: %s", txt_path.name)
        return None
    _file_prefix, dharmaseed_id, title_slug = parsed

    raw = txt_path.read_text(encoding="utf-8", errors="replace")
    body = _strip_transcript(raw)
    if not body or len(body) < 200:
        logger.warning("Empty / short body in %s (%d chars)", txt_path.name, len(body))
        return None

    meta = talks_index.get(dharmaseed_id, {})
    title = meta.get("title") or _humanise_slug(title_slug)
    date_iso = meta.get("date") or ""

    body_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()

    canonical_id = f"{teacher_slug}_{dharmaseed_id}"

    return TalkRecord(
        canonical_id=canonical_id,
        dharmaseed_id=dharmaseed_id,
        title=title,
        date_iso=date_iso,
        body=body,
        body_hash=body_hash,
        file_path=txt_path,
        talk_meta=meta,
    )


def _humanise_slug(slug: str) -> str:
    """Best-effort title from a filename slug (fallback when json-meta missing).

    ``opening_the_door`` → ``Opening the Door``. Stop-words stay
    lowercase per minimal title-casing — a one-liner, not a proper
    English title-caser, but readable enough for the ~3 talks where
    metadata is missing (see concept-37 §«461 vs 458»).
    """
    words = slug.replace("_", " ").split()
    if not words:
        return slug
    return " ".join(w.capitalize() if i == 0 else _smart_case(w) for i, w in enumerate(words))


_LOWER_TITLE_WORDS = frozenset({"a", "an", "the", "of", "in", "on", "and", "or", "to", "for"})


def _smart_case(word: str) -> str:
    return word if word.lower() in _LOWER_TITLE_WORDS else word.capitalize()


# ---------------------------------------------------------------------------
# Deterministic context prefix
# ---------------------------------------------------------------------------


def _build_context_text(
    *,
    title: str,
    teacher_name: str,
    date_iso: str,
    dharmaseed_id: str,
) -> str:
    """Single-sentence narrative stamp prepended to each child chunk.

    Deterministic — no LLM. Carries the four anchor facts BGE-M3 needs
    to disambiguate teacher / topic / time across thousands of similar
    insight-tradition talks.

    Empty or unknown values are quietly elided rather than producing
    awkward placeholders ("titled ''"). This keeps the prefix clean
    when a transcript has no matching json metadata.
    """
    parts: list[str] = ["Excerpt from a recorded dharma talk"]
    if title:
        parts.append(f'titled "{title}"')
    if teacher_name:
        parts.append(f"by {teacher_name}")
    if date_iso:
        parts.append(f"recorded {date_iso}")
    sentence = ", ".join(parts) + "."
    if dharmaseed_id:
        sentence += f" Source: dharmaseed.org/talks/{dharmaseed_id}."
    return sentence


_CONTEXT_VERSION = "deterministic-v1"
_CONTEXT_MODEL = "metadata-prefix-v1"


# ---------------------------------------------------------------------------
# Database loaders
# ---------------------------------------------------------------------------


async def _require_author(session: AsyncSession, slug: str) -> Author:
    author = (
        await session.execute(sa.select(Author).where(Author.slug == slug))
    ).scalar_one_or_none()
    if author is None:
        raise LookupError(
            f"Author with slug={slug!r} not seeded — add a migration first "
            "(see alembic/versions/20260509_007_dharmaseed_source_type.py)."
        )
    return author


async def _load_talk(
    session: AsyncSession,
    *,
    record: TalkRecord,
    teacher_author: Author,
    consent_ledger_ref: str,
    license_str: str,
) -> tuple[bool, int, int]:
    """Insert one talk's FRBR + chunks. Returns (skipped, n_parents, n_children).

    Idempotent via ``content_hash`` on Instance — same body hash → skip.
    """
    existing = (
        await session.execute(
            sa.select(Instance).where(Instance.content_hash == record.body_hash).limit(1)
        )
    ).scalar_one_or_none()
    if existing is not None:
        return True, 0, 0

    work = await _get_or_create_work(session, record=record)
    expression = await _get_or_create_expression(
        session,
        work_id=work.id,
        author_id=teacher_author.id,
        record=record,
        license_str=license_str,
        consent_ledger_ref=consent_ledger_ref,
    )

    instance = Instance(
        expression_id=expression.id,
        source_url=f"https://dharmaseed.org/talks/{record.dharmaseed_id}/",
        source_format="whisperai-large-v3-text",
        retrieved_at=datetime.now(UTC),
        content_hash=record.body_hash,
        storage_path=str(record.file_path),
        metadata_json={
            "dharmaseed_id": record.dharmaseed_id,
            "talks_json_meta": record.talk_meta,
            "transcription_engine": "WhisperAI Pro (Whisper large-v3)",
        },
    )
    session.add(instance)
    await session.flush()

    parents = chunk_talk(record.body)
    teacher_name = teacher_author.name
    n_parents = 0
    n_children = 0
    next_sequence = 0
    for parent in parents:
        parent_row = Chunk(
            instance_id=instance.id,
            sequence=next_sequence,
            text=parent.text,
            text_ascii_fold=to_ascii_fold(parent.text),
            token_count=parent.token_count,
            is_parent=True,
            segment_id=None,  # talks have no segment IDs
            metadata_json={
                "stage": "parent",
                "position": parent.position,
                "child_count": len(parent.children),
            },
        )
        session.add(parent_row)
        await session.flush()
        n_parents += 1
        next_sequence += 1

        for child in parent.children:
            session.add(
                Chunk(
                    instance_id=instance.id,
                    parent_chunk_id=parent_row.id,
                    sequence=next_sequence,
                    text=child.text,
                    text_ascii_fold=to_ascii_fold(child.text),
                    token_count=child.token_count,
                    is_parent=False,
                    segment_id=None,
                    context_text=_build_context_text(
                        title=record.title,
                        teacher_name=teacher_name,
                        date_iso=record.date_iso,
                        dharmaseed_id=record.dharmaseed_id,
                    ),
                    context_version=_CONTEXT_VERSION,
                    context_model=_CONTEXT_MODEL,
                    metadata_json={
                        "stage": "child",
                        "position_in_parent": child.position_in_parent,
                    },
                )
            )
            n_children += 1
            next_sequence += 1
    await session.flush()
    return False, n_parents, n_children


async def _get_or_create_work(session: AsyncSession, *, record: TalkRecord) -> Work:
    """Look up a Work by canonical_id, creating it on first ingest."""
    work = (
        await session.execute(sa.select(Work).where(Work.canonical_id == record.canonical_id))
    ).scalar_one_or_none()
    if work is not None:
        return work
    work = Work(
        canonical_id=record.canonical_id,
        title=record.title,
        title_pali=None,
        tradition_code="pragmatic_dharma",
        primary_language_code="eng",
        source_type="dharmaseed_talk",
        is_restricted=False,
        metadata_json={
            "dharmaseed_id": record.dharmaseed_id,
            "date": record.date_iso,
        },
    )
    session.add(work)
    await session.flush()
    return work


async def _get_or_create_expression(
    session: AsyncSession,
    *,
    work_id: UUID,
    author_id: UUID,
    record: TalkRecord,
    license_str: str,
    consent_ledger_ref: str,
) -> Expression:
    """Look up by (work_id, author_id, language) — Burbea has one EN per talk."""
    existing = (
        await session.execute(
            sa.select(Expression).where(
                Expression.work_id == work_id,
                Expression.author_id == author_id,
                Expression.language_code == "eng",
            )
        )
    ).scalar_one_or_none()
    if existing is not None:
        return existing
    expression = Expression(
        work_id=work_id,
        author_id=author_id,
        language_code="eng",
        title=record.title,
        publication_year=int(record.date_iso[:4]) if record.date_iso[:4].isdigit() else None,
        edition_note="WhisperAI large-v3 transcription",
        license=license_str,
        consent_ledger_ref=consent_ledger_ref,
        metadata_json={"date": record.date_iso},
    )
    session.add(expression)
    await session.flush()
    return expression


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


async def _run(args: argparse.Namespace) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    settings = get_settings()

    transcripts_dir = Path(args.transcripts_dir)
    talks_json_path = Path(args.talks_json)
    if not transcripts_dir.is_dir():
        print(f"ERROR: transcripts dir not found: {transcripts_dir}", file=sys.stderr)
        return 1
    if not talks_json_path.is_file():
        print(f"ERROR: talks json not found: {talks_json_path}", file=sys.stderr)
        return 1

    talks_index = _build_talks_index(talks_json_path)
    print(f"Loaded {len(talks_index)} talk-metadata entries from {talks_json_path.name}")

    txt_files = sorted(transcripts_dir.glob("*.txt"))
    print(f"Found {len(txt_files)} .txt files in {transcripts_dir}")

    engine = create_async_engine(settings.database_url, future=True, echo=False)
    session_maker = async_sessionmaker(engine, expire_on_commit=False)
    stats = IngestStats()
    start = time.monotonic()
    try:
        async with session_maker() as session:
            teacher_author = await _require_author(session, args.teacher_slug)
            consent_ledger_ref = f"local-dev/dharmaseed-{args.teacher_slug}-pilot.yaml"
            for i, txt_path in enumerate(txt_files, start=1):
                stats.talks_seen += 1
                try:
                    record = _build_talk_record(
                        txt_path=txt_path,
                        talks_index=talks_index,
                        teacher_slug=args.teacher_slug,
                    )
                    if record is None:
                        stats.talks_skipped += 1
                        continue
                    skipped, n_p, n_c = await _load_talk(
                        session,
                        record=record,
                        teacher_author=teacher_author,
                        consent_ledger_ref=consent_ledger_ref,
                        license_str=args.license,
                    )
                    if skipped:
                        stats.talks_skipped += 1
                    else:
                        stats.talks_inserted += 1
                        stats.parents_inserted += n_p
                        stats.children_inserted += n_c
                except Exception as exc:  # noqa: BLE001
                    stats.talks_errored += 1
                    logger.exception("Failed on %s: %s", txt_path.name, exc)
                if i % args.commit_every == 0:
                    await session.commit()
                    elapsed = time.monotonic() - start
                    print(
                        f"[{i}/{len(txt_files)}] commit OK — "
                        f"inserted={stats.talks_inserted} "
                        f"skipped={stats.talks_skipped} "
                        f"errors={stats.talks_errored} "
                        f"parents={stats.parents_inserted} "
                        f"children={stats.children_inserted} "
                        f"elapsed={elapsed:.1f}s"
                    )
            await session.commit()
    finally:
        await engine.dispose()

    elapsed = time.monotonic() - start
    print()
    print("=== rag-day-37 dharmaseed ingest finished ===")
    print(f"  teacher:           {args.teacher_slug}")
    print(f"  txt files seen:    {stats.talks_seen}")
    print(f"  talks inserted:    {stats.talks_inserted}")
    print(f"  talks skipped:     {stats.talks_skipped}")
    print(f"  talks errored:     {stats.talks_errored}")
    print(f"  parents inserted:  {stats.parents_inserted}")
    print(f"  children inserted: {stats.children_inserted}")
    print(f"  wallclock:         {elapsed:.1f}s")
    if stats.talks_errored > 0:
        print()
        print("Some talks errored — check log above. Re-run is idempotent.")
        return 2
    return 0


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Ingest Dharmaseed transcripts into Dharma-RAG")
    p.add_argument("--teacher-slug", required=True, help="Author slug (e.g. rob_burbea)")
    p.add_argument(
        "--transcripts-dir",
        required=True,
        help="Directory of .txt transcripts (e.g. Q:/dharmaseed/transcripts/rob_burbea)",
    )
    p.add_argument(
        "--talks-json",
        required=True,
        help="Per-teacher metadata json (e.g. Q:/dharmaseed/rob_burbea_talks.json)",
    )
    p.add_argument(
        "--license",
        default="CC-BY-NC-ND-4.0",
        help="License stamp on Expression rows. Default Dharmaseed canonical.",
    )
    p.add_argument(
        "--commit-every",
        type=int,
        default=20,
        help="Commit every N talks to bound rollback cost. Default 20.",
    )
    return p.parse_args()


if __name__ == "__main__":
    raise SystemExit(asyncio.run(_run(_parse_args())))
